field: 38a113f2-a291-41e2-b9c2-44d10e17e002
fieldLayouts:
  d55b9fa1-e48e-481e-b2fa-df45eeeb47a4:
    tabs:
      -
        elements:
          -
            fieldUid: b7eebe7f-d12a-43be-beca-b0cfde25d24f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 750bf8a5-d885-4e91-b6fc-f2a61b8bed05
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  750bf8a5-d885-4e91-b6fc-f2a61b8bed05:
    contentColumnType: string
    fieldGroup: null
    handle: sectionOptions
    instructions: ''
    name: 'Section Options'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - f0b41dad-b329-42a7-ab95-b0e4fb9192a8
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - befbd4ae-36a4-4ce5-880e-52249518544d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5a040c37-5377-4d30-b7f3-b3092a8b2571
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ba1dc330-3e8d-4476-ab2f-8e49e3df5a12
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 81785d0b-7109-417a-8045-93379aa06e06
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e2abd5ee-fc76-4bd1-bea0-bcbaed948d34
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3e69ffef-aed6-4b84-aa1c-8142a37a37e9
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_sectionoptions}}'
      fieldLayout: row
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  b7eebe7f-d12a-43be-beca-b0cfde25d24f:
    contentColumnType: string
    fieldGroup: null
    handle: sectionContent
    instructions: 'Banners can be used a page headings or as section dividers.'
    name: 'Section Content'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 89ba1114-a89f-413a-ba68-22b4fc308344
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0d49ee49-efdc-4261-b0c4-03b9ba68d541
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 129d9a9a-fa64-409b-a2d7-2e155f4f02db
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2040d379-2007-49d0-8174-64d81c95a00d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 10bacfdb-d6da-4386-b08f-caf41fccf2f3
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 10b21965-baea-4da0-8f33-00dea263bba7
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e550cd8f-f83d-49d9-b1fb-81a6de908627
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - de7668b5-4e20-4fb1-841c-a8a48aff88a0
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 72fc6ec3-e059-4fab-a924-55cd4baf7659
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6738616e-7409-4184-9d40-191c5767625c
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_sectioncontent}}'
      fieldLayout: row
      maxRows: ''
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add a banner'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: banner
name: Banner
sortOrder: 1
