field: 38a113f2-a291-41e2-b9c2-44d10e17e002
fieldLayouts:
  4cac389a-1610-4142-824b-cb25541097aa:
    tabs:
      -
        elements:
          -
            fieldUid: 221a5868-d1f5-41ba-97ad-73b39ae9e6bf
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: db9e55f2-16bc-4874-8464-69449a4fa242
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 65192306-1236-48d9-b750-5fea35c80448
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  221a5868-d1f5-41ba-97ad-73b39ae9e6bf:
    contentColumnType: text
    fieldGroup: null
    handle: sectionIntroduction
    instructions: ''
    name: 'Section Introduction'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  65192306-1236-48d9-b750-5fea35c80448:
    contentColumnType: string
    fieldGroup: null
    handle: sectionOptions
    instructions: ''
    name: 'Section Options'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - f59912a8-ceb1-43dd-9602-d36e747aa9f6
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5f2901c1-7414-4292-97bc-7c0d5dba5d8e
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2efda75e-c325-4d6b-beb6-8b8e5006c9a9
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7f0eb7c3-bfb8-4c9f-b964-d7699d856f1b
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b493cebc-941d-4f3f-89bc-6c8178f5bea0
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 22e0e3e7-b3a4-4332-bd8d-0fa732734765
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b45255b1-3359-4c28-97df-a9aad552b07b
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_sectionoptions}}'
      fieldLayout: row
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  db9e55f2-16bc-4874-8464-69449a4fa242:
    contentColumnType: string
    fieldGroup: null
    handle: sectionContent
    instructions: 'Add up to 6 spotlights per section.'
    name: 'Section Content'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 24a8588d-7a76-40e6-9382-280d572c9813
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3108f190-2b2a-453f-8488-454796f4b25b
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - bc51ecc0-b732-4b81-b2c8-e15671cf3bb7
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 71098194-d209-420e-b025-c52fbbd4fae2
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_sectioncontent}}'
      fieldLayout: row
      maxRows: '6'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add a spotlight'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: spotlights
name: Spotlights
sortOrder: 3
