fieldLayouts:
  b3b2dfd1-a9df-493d-8a6a-31483fd736ff:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 632bf12e-8cf8-481e-8664-132ea931fe89
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84b51837-3d6b-4763-8ebd-cd7b22edb675
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f11613a0-3ab2-4509-ae1d-62987191af53
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Search
        sortOrder: 2
handle: blog
hasTitleField: true
name: Blog
section: 321cab46-2367-4de0-b83b-2f4adad0e412
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
