fieldLayouts:
  44e18fc8-aeb9-426d-98e2-36ffe3258ac1:
    tabs:
      -
        elements:
          -
            fieldUid: f11613a0-3ab2-4509-ae1d-62987191af53 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Search
        sortOrder: 1
handle: home
hasTitleField: false
name: Home
section: badfd65c-ecad-4db4-8651-b5616f2ca0df # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
