fieldLayouts:
  4251c36c-b4d3-4918-a7f3-a7b7a5e51ccd:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 632bf12e-8cf8-481e-8664-132ea931fe89 # Description
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84b51837-3d6b-4763-8ebd-cd7b22edb675 # Featured Image
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 38a113f2-a291-41e2-b9c2-44d10e17e002 # Content Builder
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f11613a0-3ab2-4509-ae1d-62987191af53 # SEO
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Search
        sortOrder: 2
handle: pages
hasTitleField: true
name: Pages
section: 511fcb81-8aa7-4b19-b1c0-4134cda61282 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
