contentColumnType: text
fieldGroup: e1d393b0-7aa4-4ca0-94e3-0eeca1b1423d
handle: copyright
instructions: ''
name: Copyright
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
