field: e48f1d2f-9b9e-44ea-b85c-cbf4a8c0373c
fieldLayouts:
  da536645-a688-4393-bc5c-421c222f6e4b:
    tabs:
      -
        elements:
          -
            fieldUid: 81ff0268-4939-4702-9cd0-8f7ae0eebe9a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 520435a7-5b4e-43cc-ad17-0b5d43ebf127
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed49068f-d7d5-40f0-94ae-78306dbef025
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 33bc2592-f44b-4aa4-9fc9-a23089d45f0f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99becc6b-78b8-4761-b8b0-2763995f87ea
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8d958cae-81d7-4915-bf41-58cd070a4bf3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27724e67-bfbb-4948-8c6e-063e5ae35f27
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c3f9098d-01e9-413c-86a9-8912f752d04a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  27724e67-bfbb-4948-8c6e-063e5ae35f27:
    contentColumnType: text
    fieldGroup: null
    handle: sectionId
    instructions: ''
    name: 'Section ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  33bc2592-f44b-4aa4-9fc9-a23089d45f0f:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  520435a7-5b4e-43cc-ad17-0b5d43ebf127:
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: ''
    name: 'Section Padding'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  81ff0268-4939-4702-9cd0-8f7ae0eebe9a:
    contentColumnType: boolean
    fieldGroup: null
    handle: fullWidth
    instructions: ''
    name: 'Full Width'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8d958cae-81d7-4915-bf41-58cd070a4bf3:
    contentColumnType: boolean
    fieldGroup: null
    handle: textLight
    instructions: ''
    name: 'Text Light'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  99becc6b-78b8-4761-b8b0-2763995f87ea:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c3f9098d-01e9-413c-86a9-8912f752d04a:
    contentColumnType: text
    fieldGroup: null
    handle: sectionClass
    instructions: ''
    name: 'Section Class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed49068f-d7d5-40f0-94ae-78306dbef025:
    contentColumnType: string
    fieldGroup: null
    handle: verticalAlignment
    instructions: ''
    name: 'Vertical Alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - align-items-start
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Middle
            -
              - value
              - align-items-center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - align-items-end
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Equal Height'
            -
              - value
              - ''
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
