field: 3b59abce-3d4d-468b-8520-44b2f3db37d9
fieldLayouts:
  19617606-b585-4903-b9f3-c5e90615013b:
    tabs:
      -
        elements:
          -
            fieldUid: 572c0ae0-d606-46a0-b420-737f8b63cd34
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 881d8083-6117-4f6f-bf60-096741cd45bc
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  572c0ae0-d606-46a0-b420-737f8b63cd34:
    contentColumnType: text
    fieldGroup: null
    handle: embedUrl
    instructions: ''
    name: 'Embed URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  881d8083-6117-4f6f-bf60-096741cd45bc:
    contentColumnType: string
    fieldGroup: null
    handle: aspectRatio
    instructions: ''
    name: 'Aspect Ratio'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Aspect 21:9'
            -
              - value
              - embed-responsive-21by9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Aspect 16:9'
            -
              - value
              - embed-responsive-16by9
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Aspect 4:3'
            -
              - value
              - embed-responsive-4by3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Aspect 1:1'
            -
              - value
              - embed-responsive-1by1
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
