field: e02d24e2-305c-41be-ab36-cceeab10d48b
fieldLayouts:
  8c0dbd88-4227-431f-b6d7-0700666140a3:
    tabs:
      -
        elements:
          -
            fieldUid: b5634a68-6dfb-4d6c-970f-44e24b5bb0c5
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d3cb8f4f-4876-488e-8bde-1aa0d2a63330
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b5634a68-6dfb-4d6c-970f-44e24b5bb0c5:
    contentColumnType: text
    fieldGroup: null
    handle: accordionTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d3cb8f4f-4876-488e-8bde-1aa0d2a63330:
    contentColumnType: text
    fieldGroup: null
    handle: accordionContent
    instructions: ''
    name: Content
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
