field: bc352a13-dde4-4288-bb0a-3b69120c7e38
fieldLayouts:
  51b9c050-858c-469d-859a-ede642da66ec:
    tabs:
      -
        elements:
          -
            fieldUid: ab3f463c-f4c1-4c1b-a2fe-18bf4ec15a8a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b57cbc5a-1dee-49c0-b6ce-3b27f716c5cc
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6147d033-9de6-4ea5-b803-87bbaa4d99f5
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6efd6a5d-f5d5-411c-a817-b3dbc70d4a15
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4bec3b94-5008-4b0f-af4f-7f6eeef446e7
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56bc1310-bc25-4230-9360-eb7fc6787e0e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4a888d1-7af6-45bd-b053-56776f244438
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6627619c-d935-4f81-9938-f6587064cc74
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cbe22317-b2e5-4f73-9162-64b47cf804c3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4bec3b94-5008-4b0f-af4f-7f6eeef446e7:
    contentColumnType: boolean
    fieldGroup: null
    handle: alignCenter
    instructions: ''
    name: 'Align Center'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  56bc1310-bc25-4230-9360-eb7fc6787e0e:
    contentColumnType: boolean
    fieldGroup: null
    handle: inlineButtons
    instructions: ''
    name: 'Inline Buttons'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  6147d033-9de6-4ea5-b803-87bbaa4d99f5:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  6627619c-d935-4f81-9938-f6587064cc74:
    contentColumnType: text
    fieldGroup: null
    handle: sectionId
    instructions: ''
    name: 'Section ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6efd6a5d-f5d5-411c-a817-b3dbc70d4a15:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a4a888d1-7af6-45bd-b053-56776f244438:
    contentColumnType: boolean
    fieldGroup: null
    handle: textLight
    instructions: ''
    name: 'Text Light'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ab3f463c-f4c1-4c1b-a2fe-18bf4ec15a8a:
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: ''
    name: 'Section Padding'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b57cbc5a-1dee-49c0-b6ce-3b27f716c5cc:
    contentColumnType: string
    fieldGroup: null
    handle: verticalAlignment
    instructions: ''
    name: 'Vertical Alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - align-items-start
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Middle
            -
              - value
              - align-items-center
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - align-items-end
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cbe22317-b2e5-4f73-9162-64b47cf804c3:
    contentColumnType: text
    fieldGroup: null
    handle: sectionClass
    instructions: ''
    name: 'Section Class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
