field: cb9a8288-ddc5-41b4-a78b-338d3d147a37 # Section Options
fieldLayouts:
  0108f4fc-3a0a-43bf-9e5a-383dfd750016:
    tabs:
      -
        elements:
          -
            fieldUid: ea390df1-a6c4-4691-b0a9-1692ba9251be # Full Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e7dd5cae-759b-424b-831d-23449b3331ba # Section Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bef774ad-e70d-4e96-a3e5-3a917e4b6b9e # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 03b9360c-0ec9-4b16-92ce-d2d1bcff4101 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b8ceeb74-8113-4c73-a4c6-052da66c036c # Text Light
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54095cb1-ccf7-45fc-85ba-79a06489eca1 # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bf334030-d954-4bdf-bf73-a5287486c1c0 # Section Class
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  03b9360c-0ec9-4b16-92ce-d2d1bcff4101: # Background Image
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:244c8899-c0b5-46f0-b74e-f81a9af913b2' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  54095cb1-ccf7-45fc-85ba-79a06489eca1: # Section ID
    contentColumnType: text
    fieldGroup: null
    handle: sectionId
    instructions: ''
    name: 'Section ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b8ceeb74-8113-4c73-a4c6-052da66c036c: # Text Light
    contentColumnType: boolean
    fieldGroup: null
    handle: textLight
    instructions: ''
    name: 'Text Light'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  bef774ad-e70d-4e96-a3e5-3a917e4b6b9e: # Background Colour
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  bf334030-d954-4bdf-bf73-a5287486c1c0: # Section Class
    contentColumnType: text
    fieldGroup: null
    handle: sectionClass
    instructions: ''
    name: 'Section Class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e7dd5cae-759b-424b-831d-23449b3331ba: # Section Padding
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: ''
    name: 'Section Padding'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ea390df1-a6c4-4691-b0a9-1692ba9251be: # Full Width
    contentColumnType: boolean
    fieldGroup: null
    handle: fullWidth
    instructions: ''
    name: 'Full Width'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
