field: 6b516e11-ab0b-4f93-8044-0664e8fff370
fieldLayouts:
  d5ae9c58-37b1-448f-8cd8-91f907e6fad2:
    tabs:
      -
        elements:
          -
            fieldUid: 991e0ff0-73df-4864-a2da-8a88fb368a3e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ede1d627-10a2-4a6c-a6c1-1569debd98a8
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  991e0ff0-73df-4864-a2da-8a88fb368a3e:
    contentColumnType: text
    fieldGroup: null
    handle: testimonial
    instructions: ''
    name: Testimonial
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ede1d627-10a2-4a6c-a6c1-1569debd98a8:
    contentColumnType: text
    fieldGroup: null
    handle: credit
    instructions: ''
    name: Credit
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
