fieldLayouts:
  564c77c2-ca5d-4e93-97cf-e2b6a54d4974:
    tabs:
      -
        elements:
          -
            fieldUid: b315265d-d82b-4c19-854f-dbadf2e20d11
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 422c975b-8963-4f45-9088-152c7fe0e0c2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Footer Section'
        sortOrder: 1
handle: siteSettings
name: 'Site Settings'
sortOrder: 1
