enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5caa5c6f-3b72-48ac-b3fd-7f170b965d3d: # Movie Generator
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
