enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  5caa5c6f-3b72-48ac-b3fd-7f170b965d3d:
    enabledByDefault: true
    hasUrls: true
    template: pages/index
    uriFormat: '{slug}'
type: channel
